### ISSUE TITLE
Attempting to move UICollectionViewCell with drag interaction with layer.cornerRadius > 0 results in SIGABRT error.

### ISSUE THREAD

**Issue by ilevIO** [adamwulf/PerformanceBezier#8] opened 2020-01-07 07:40 UTC
When setting cell.layer.cornerRadius a non-zero value and then trying to move the cell app crashes with SIGABRT signal.
Error occurs in line 221 UIBezierPath+Performance.m: 
`[aCoder encodeObject:self.pathProperties forKey:@"pathProperties"];`
Commenting out all the swizzling _solves_ the problem (if it's appropriate to say so).
That's a project with the error replicated: 
https://github.com/ilevIO/CollectionViewDragNDropTestWithClippingBezierFramework

**Comment by adamwulf** [comment] 2020-01-07 07:52
Thanks for the report! And bigger thanks for the sample project - I was able to reproduce the problem immediately thanks to your work on that.

I've just pushed a fix in commit `98b772617` in the master branch. The problem was that the Bezier properties supported `NSCoding` but not `NSSecureCoding`, but that's now been fixed.

If you pull the master branch down and rebuild the framework, everything should be fine now.

Thanks!

**Closed as completed by adamwulf** 2020-01-07 07:52 UTC
Labels: bug
